<?php
declare(strict_types=1);
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

require_once('../vendor/autoload.php');

function domail( $to,$toname,$sub,$body) {
    $mail = new PHPMailer(true);
    //Server settings
    try {
        $mail->SMTPDebug = 0;                      //Enable verbose debug output
        $mail->isSMTP();                                            //Send using SMTP
        $mail->Host       = "smtp.hostinger.com";                     //Set the SMTP server to send through
        $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
        $mail->Username   = "no-reply@karma.titanslab.in";                     //SMTP username
        $mail->Password   = "#noPass123";                               //SMTP password
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;           //Enable implicit TLS encryption
        $mail->Port       = 465;                     //Set the SMTP port
        $mail->addCustomHeader('MIME-Version', '1.0');
        $mail->addCustomHeader('DATE', date('r'));

        //Recipients
        $mail->setFrom('no-reply@karma.titanslab.in', 'Karma Foundation');
        $mail->addAddress( $to, $toname );     // Add a recipient
        $mail->Subject = $sub;
        $body.="<br><br><h6>This Mail was automatically generated by the karmafoundation.co. Please do not reply to this email.</h6>";
        $mail->Body    = $body;
        // Content
        $mail->isHTML(true);
        $mail->send();

        return true;
    } catch (Exception $e) {
        return false;
        // return "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
    }
}
?>